In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/opt/homebrew/lib/python3.9/site-packages/numpy/__init__.py'>

In [6]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [7]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [8]:
a2.shape

(1, 6)

In [57]:
rng = np.random.default_rng(1234)
vals = rng.standard_normal(100)

In [58]:

vals

array([-1.60383681,  0.06409991,  0.7408913 ,  0.15261919,  0.86374389,
        2.91309922, -1.47882336,  0.94547297, -1.66613546,  0.34374458,
       -0.51244371,  1.32375896, -0.86028019,  0.5194932 , -1.26514372,
       -2.15913901,  0.43473395,  1.73328932,  0.52013416, -1.00216579,
        0.26834554,  0.7671747 ,  1.19127203, -1.15741081,  0.6962794 ,
        0.35138369, -0.03241508,  0.01318158, -0.67924997, -0.62053203,
        1.33121422,  0.25883851, -0.48148392, -2.49178962, -0.87656377,
       -0.50550913, -1.28312917, -1.33032842,  0.82599258, -0.24721501,
       -1.69970612, -1.33515287, -0.29963889,  1.1148069 , -1.50640885,
        1.59011208, -0.48732518, -1.71110219,  0.51309021,  1.43709192,
       -0.22180411,  0.6488165 , -0.31789119, -0.01097826,  1.6654165 ,
        0.89578643, -1.20260119,  2.79962711, -1.02119625,  0.848107  ,
        0.49808261, -0.08444164,  0.20249333, -0.16380578,  0.83705971,
       -0.71243966, -1.17414987,  0.47526795,  1.73739481, -0.13

In [52]:
np.std(vals)

1.1204522311616263